FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm config set strict-ssl false
RUN npm install

COPY . .
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npx ng build CHEMILAB_MANAGEMENT_FRONT --configuration production

FROM nginx:alpine

COPY --from=builder /app/dist/CHEMILAB_MANAGEMENT_FRONT/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]