# Construir angular
FROM node:20-alpine AS build


# Instalar dependencias
COPY package*.json .
RUN npm ci


# Copiar codigo y compilar para producción
COPY . .
RUN npm run build -- --configuration production

# Nginx para servir estaticos
FROM nginx:alpine

COPY --from=builder /dist/CHEMILAB_MANAGEMENT_FRONT/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 86

CMD ["nginx", "-g", "daemon off;"]