FROM node:20-alpine AS build
WORKDIR /app

# Instalar dependencias
COPY . .
RUN npm ci && npx ng build

FROM nginx:alpine


COPY --from=build /app/dist/CHEMILAB_MANAGEMENT_FRONT/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 86

CMD ["nginx", "-g", "daemon off;"]