#frontend/nginx-spa.conf
server {
    
    listen 4500;
    
    root /usr/share/nginx/html;
    
    index index.html
    
    location / {
        
        try_files $uri $uri/ /index.html;
        
    }
    
}