name: Build & Deploy

on:
  push:
    branches:
      - deploy

env:
  REGISTRY: ghcr.io
  IMAGE_BACK: ghcr.io/${{ github.repository_owner }}/miapp-back
  IMAGE_FRONT: ghcr.io/${{ github.repository_owner }}/miapp-front

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build y Push — Backend
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/miapp-back:latest

      - name: Build y Push — Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/miapp-front:latest

      - name: Deploy en servidor via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/CHEMILAB_MANAGEMENT/planner_front/
            echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ secrets.SERVER_USER }} --password-stdin
            docker compose pull
            docker compose up -d --force-recreate
            docker image prune -f
